baseurl = "/"
title = "Bari Abbassi"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
canonifyurls = true
pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "Bari Abbassi"

[params]
    author = "Bari Abbassi"

    info = "Hi, my name is Bari.  I'm a Software Engineer.  I solve problems using Software.  I also take pictures for fun."

    description = "Bari Abbassi's personal website"

    keywords = "backend, developer, blockchain, amsterdam, fintech"

    avatarurl = "/profile.jpg"
    favicon_32 = "/favicon-32x32.png"
    favicon_16 = "/favicon-16x16.png"

    #footercontent = "Enter a text here."
    hidecredits = true
    hidecopyright = true
    rtl = false
    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/bariabbassi/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/bariabbassi/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/bariabbassi/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 3
    url = "https://instagram.com/bariabbassi/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 3
    url = "https://medium.com/@BariAbbassi/"
[[params.social]]
    name = "Envelope"
    icon = "far fa-envelope fa-2x"
    weight = 1
    url = "mailto:bari@abbas.si"

# Menu links
#[[menu.main]]
    #name = "About"
    #weight = 2
    #url = "/about/"
