baseurl = "/"
title = "Bari Abbassi - Blockchain Engineer"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
canonifyurls = true
pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "Bari Abbassi"

[params]
    author = "Bari Abbassi"

    info = "Blockchain Engineer. Helped companies like OWNEST and CRATR build robust Blockchain solutions. Currently conducting research on Blockchain interoperability at Tohoku University."

    description = "Bari Abbassi's personal website"

    keywords = "bari abbassi,bariabbassi,bari,abbassi,blockchain,software,developer,blockchain engineer, software developer,bitcoin,ethereum,solidity,web3,cosmos,cosmos sdk,cosmos-sdk,cosmos network,tendermint,polkadot,substrate,interledger,ilp,xrp,ripple,hyperledger,hyperledger fabric,corda,r3,dlt,go,golang,decentralization"

    avatarurl = "/profile.jpg"
    favicon_32 = "/favicon-32x32.png"
    favicon_16 = "/favicon-16x16.png"

    #footercontent = "Enter a text here."
    hidecredits = true
    hidecopyright = true
    rtl = false
    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/bariabbassi/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/bariabbassi/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/bariabbassi/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 3
    url = "https://medium.com/@BariAbbassi/"
[[params.social]]
    name = "Envelope"
    icon = "far fa-envelope fa-2x"
    weight = 1
    url = "mailto:abbassibari@gmail.com"

# Menu links
#[[menu.main]]
    #name = "About"
    #weight = 2
    #url = "/about/"
